apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: "adminpassword"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  type: NodePort
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/nextcloud:stable-apache

          ports:
            - containerPort: 80

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi

          env:
            - name: NEXTCLOUD_UPDATE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-configmap
                  key: NEXTCLOUD_UPDATE

            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-configmap
                  key: NEXTCLOUD_TRUSTED_DOMAINS

            - name: POSTGRES_HOST
              value: postgres-service

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: NEXTCLOUD_ADMIN_USER
              value: admin

            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: NEXTCLOUD_ADMIN_PASSWORD

          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html

          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
